# Generated by Django 3.2 on 2021-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dispatcher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcher',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
